"""Conservative payroll master-data defaults extracted from za_local."""

DEFAULT_SARS_PAYROLL_CODES = [{'code': '3601',
  'description': 'Income - Gross Remuneration',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 10},
 {'code': '3605',
  'description': 'Income - Annual Payment',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 20},
 {'code': '3607',
  'description': 'Income - Overtime',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 30},
 {'code': '3701',
  'description': 'Income - Travel Allowance',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 40},
 {'code': '3702',
  'description': 'Income - Other Allowances',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 50},
 {'code': '3704',
  'description': 'Income - Subsistence Allowance',
  'category': 'Income',
  'tax_treatment': 'Non-Taxable',
  'print_sequence': 60},
 {'code': '3713',
  'description': 'Income - Uniform Allowance',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 70},
 {'code': '3801',
  'description': 'Income - General Taxable Fringe Benefits',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 75},
 {'code': '3802',
  'description': 'Income - Use of Motor Vehicle',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 80},
 {'code': '3805',
  'description': 'Income - Residential Accommodation',
  'category': 'Income',
  'tax_treatment': 'Taxable',
  'print_sequence': 85},
 {'code': '3901',
  'description': 'Income - Gratuities / Severance Benefits',
  'category': 'Income',
  'tax_treatment': 'Reference',
  'print_sequence': 90},
 {'code': '3907',
  'description': 'Income - Other Lump Sums',
  'category': 'Income',
  'tax_treatment': 'Reference',
  'print_sequence': 95},
 {'code': '4001',
  'description': 'Deduction - Pension / Provident Fund',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 100},
 {'code': '4005',
  'description': 'Deduction - Medical Scheme Fees',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 110},
 {'code': '4006',
  'description': 'Deduction - Retirement Annuity Fund',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 120},
 {'code': '4007',
  'description': 'Deduction - Group Life Insurance',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 130},
 {'code': '4008',
  'description': 'Deduction - Disability Insurance',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 140},
 {'code': '4010',
  'description': 'Deduction - Loan Repayment',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 150},
 {'code': '4102',
  'description': 'Deduction - PAYE',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 160},
 {'code': '4116',
  'description': 'Tax Credit - Medical Scheme Fees Tax Credit',
  'category': 'Tax Credit',
  'tax_treatment': 'Reference',
  'print_sequence': 170},
 {'code': '4118',
  'description': 'Tax Credit - Employment Tax Incentive',
  'category': 'Tax Credit',
  'tax_treatment': 'Reference',
  'print_sequence': 175},
 {'code': '4115',
  'description': 'Tax on Retirement Lump Sum and Severance Benefits',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 176},
 {'code': '4120',
  'description': 'Tax Credit - Additional Medical Expenses Tax Credit',
  'category': 'Tax Credit',
  'tax_treatment': 'Reference',
  'print_sequence': 180},
 {'code': '4141',
  'description': 'Deduction / Contribution - UIF',
  'category': 'Deduction',
  'tax_treatment': 'Reference',
  'print_sequence': 190},
 {'code': '4142',
  'description': 'Employer Contribution - SDL',
  'category': 'Employer Contribution',
  'tax_treatment': 'Reference',
  'print_sequence': 200},
 {'code': '4472',
  'description': 'Employer Contribution - Pension Fund',
  'category': 'Employer Contribution',
  'tax_treatment': 'Reference',
  'print_sequence': 210},
 {'code': '4474',
  'description': 'Employer Contribution - Medical Scheme',
  'category': 'Employer Contribution',
  'tax_treatment': 'Reference',
  'print_sequence': 220},
 {'code': '4475',
  'description': 'Employer Contribution - Group Life Insurance',
  'category': 'Employer Contribution',
  'tax_treatment': 'Reference',
  'print_sequence': 230},
 {'code': '4476',
  'description': 'Employer Contribution - Disability Insurance',
  'category': 'Employer Contribution',
  'tax_treatment': 'Reference',
  'print_sequence': 240},
 {'code': '4477',
  'description': 'Employer Contribution - Funeral Benefit',
  'category': 'Employer Contribution',
  'tax_treatment': 'Reference',
  'print_sequence': 250},
 {'code': '4497',
  'description': 'Employer Contribution - Other Employer Contributions',
  'category': 'Employer Contribution',
  'tax_treatment': 'Reference',
  'print_sequence': 260}]

DEFAULT_SALARY_COMPONENT_SARS_CODES = {'Basic Salary': '3601',
 'Basic': '3601',
 'Gross Salary': '3601',
 'Bonus': '3605',
 'Annual Bonus': '3605',
 'Performance Bonus': '3605',
 'Commission': '3605',
 '13th Cheque': '3605',
 'Overtime': '3607',
 'Travel Allowance': '3701',
 'Transport Allowance': '3701',
 'Housing Allowance': '3702',
 'Accommodation Allowance': '3702',
 'Cell Phone Allowance': '3702',
 'Subsistence Allowance': '3704',
 'Business Reimbursement': '3704',
 'Uniform Allowance': '3713',
 'Company Car Benefit': '3802',
 'Use of Motor Vehicle': '3802',
 'Housing Fringe Benefit': '3805',
 'Low Interest Loan Fringe Benefit': '3801',
 'Other Fringe Benefit': '3801',
 'PAYE': '4102',
 'Income Tax': '4102',
 'Employment Tax Incentive': '4118',
 'ETI': '4118',
 'UIF Employee Contribution': '4141',
 'UIF Employer Contribution': '4141',
 'UIF': '4141',
 'SDL Contribution': '4142',
 'SDL': '4142',
 'Skills Development Levy': '4142',
 'Pension Fund': '4001',
 'Provident Fund': '4001',
 'Retirement Fund': '4001',
 'Retirement Annuity Fund': '4006',
 'Medical Aid': '4005',
 'Medical Aid Contribution': '4005',
 'Medical Scheme': '4005',
 'Medical Insurance': '4005',
 'Severance Benefit': '3901',
 'Leave Payout': '3907',
 'Notice Pay': '3601',
 'Tax on Lump Sum': '4115',
 'Group Life Insurance': '4007',
 'Disability Insurance': '4008',
 'Loan Repayment': '4010',
 'Staff Loan Repayment': '4010'}

DEFAULT_IRP5_EXCLUDED_SALARY_COMPONENTS = {'Garnishee Order', 'Company Car PAYE Adjustment', 'Union Subscription'}

FRINGE_BENEFIT_SALARY_COMPONENTS = {'Company Car Benefit',
 'Company Car PAYE Adjustment',
 'Housing Fringe Benefit',
 'Low Interest Loan Fringe Benefit',
 'Other Fringe Benefit'}

DEFAULT_SALARY_COMPONENT_TREATMENTS = {'Basic': {'za_payroll_treatment': 'Regular Remuneration',
           'za_paye_inclusion_percentage': 100,
           'za_uif_applicable': 1,
           'za_sdl_applicable': 1,
           'za_coida_applicable': 1},
 'Basic Salary': {'za_payroll_treatment': 'Regular Remuneration',
                  'za_paye_inclusion_percentage': 100,
                  'za_uif_applicable': 1,
                  'za_sdl_applicable': 1,
                  'za_coida_applicable': 1},
 'Company Car Benefit': {'za_payroll_treatment': 'Regular Remuneration',
                         'za_paye_inclusion_percentage': 100,
                         'za_uif_applicable': 0,
                         'za_sdl_applicable': 0,
                         'za_coida_applicable': 0},
 'Company Car PAYE Adjustment': {'za_payroll_treatment': 'Regular Remuneration',
                                 'za_paye_inclusion_percentage': 100,
                                 'za_uif_applicable': 0,
                                 'za_sdl_applicable': 0,
                                 'za_coida_applicable': 0},
 'Housing Fringe Benefit': {'za_payroll_treatment': 'Regular Remuneration',
                            'za_paye_inclusion_percentage': 100,
                            'za_uif_applicable': 0,
                            'za_sdl_applicable': 0,
                            'za_coida_applicable': 0},
 'Low Interest Loan Fringe Benefit': {'za_payroll_treatment': 'Regular Remuneration',
                                      'za_paye_inclusion_percentage': 100,
                                      'za_uif_applicable': 0,
                                      'za_sdl_applicable': 0,
                                      'za_coida_applicable': 0},
 'Other Fringe Benefit': {'za_payroll_treatment': 'Regular Remuneration',
                          'za_paye_inclusion_percentage': 100,
                          'za_uif_applicable': 0,
                          'za_sdl_applicable': 0,
                          'za_coida_applicable': 0},
 'PAYE': {'za_payroll_treatment': 'PAYE',
          'za_paye_inclusion_percentage': 0,
          'za_uif_applicable': 0,
          'za_sdl_applicable': 0,
          'za_coida_applicable': 0},
 'UIF Employee Contribution': {'za_payroll_treatment': 'UIF',
                               'za_paye_inclusion_percentage': 0,
                               'za_uif_applicable': 0,
                               'za_sdl_applicable': 0,
                               'za_coida_applicable': 0},
 'UIF Employer Contribution': {'za_payroll_treatment': 'UIF',
                               'za_paye_inclusion_percentage': 0,
                               'za_uif_applicable': 0,
                               'za_sdl_applicable': 0,
                               'za_coida_applicable': 0},
 'SDL Contribution': {'za_payroll_treatment': 'SDL',
                      'za_paye_inclusion_percentage': 0,
                      'za_uif_applicable': 0,
                      'za_sdl_applicable': 0,
                      'za_coida_applicable': 0},
 'Transport Allowance': {'za_payroll_treatment': 'Fixed Travel Allowance',
                         'za_paye_inclusion_percentage': 80,
                         'za_uif_applicable': 1,
                         'za_sdl_applicable': 1,
                         'za_coida_applicable': 1},
 'Travel Allowance': {'za_payroll_treatment': 'Fixed Travel Allowance',
                      'za_paye_inclusion_percentage': 80,
                      'za_uif_applicable': 1,
                      'za_sdl_applicable': 1,
                      'za_coida_applicable': 1},
 'Performance Bonus': {'za_payroll_treatment': 'Annual Payment',
                       'za_paye_inclusion_percentage': 100,
                       'za_uif_applicable': 1,
                       'za_sdl_applicable': 1,
                       'za_coida_applicable': 1,
                       'za_variable_pay_treatment': 'Once-Off Full Tax'},
 '13th Cheque': {'za_payroll_treatment': 'Annual Payment',
                 'za_paye_inclusion_percentage': 100,
                 'za_uif_applicable': 1,
                 'za_sdl_applicable': 1,
                 'za_coida_applicable': 1,
                 'za_variable_pay_treatment': 'Once-Off Full Tax'},
 'Commission': {'za_payroll_treatment': 'Commission',
                'za_paye_inclusion_percentage': 100,
                'za_uif_applicable': 1,
                'za_sdl_applicable': 1,
                'za_coida_applicable': 1,
                'za_variable_pay_treatment': 'Once-Off Full Tax'},
 'Overtime': {'za_payroll_treatment': 'Overtime',
              'za_paye_inclusion_percentage': 100,
              'za_uif_applicable': 1,
              'za_sdl_applicable': 1,
              'za_coida_applicable': 1,
              'za_variable_pay_treatment': 'Once-Off Full Tax'},
 'Medical Aid Contribution': {'za_payroll_treatment': 'Medical Aid',
                              'za_paye_inclusion_percentage': 0,
                              'za_uif_applicable': 0,
                              'za_sdl_applicable': 0,
                              'za_coida_applicable': 0},
 'Employee Pension Fund Contribution': {'za_payroll_treatment': 'Retirement Fund',
                                        'za_paye_inclusion_percentage': 0,
                                        'za_uif_applicable': 0,
                                        'za_sdl_applicable': 0,
                                        'za_coida_applicable': 0},
 'Severance Benefit': {'za_payroll_treatment': 'Severance Benefit',
                       'za_paye_inclusion_percentage': 100,
                       'za_uif_applicable': 0,
                       'za_sdl_applicable': 0,
                       'za_coida_applicable': 0,
                       'za_variable_pay_treatment': 'Manual Review'},
 'Leave Payout': {'za_payroll_treatment': 'Leave Payout',
                  'za_paye_inclusion_percentage': 100,
                  'za_uif_applicable': 1,
                  'za_sdl_applicable': 1,
                  'za_coida_applicable': 1,
                  'za_variable_pay_treatment': 'Once-Off Full Tax'},
 'Notice Pay': {'za_payroll_treatment': 'Notice Pay',
                'za_paye_inclusion_percentage': 100,
                'za_uif_applicable': 1,
                'za_sdl_applicable': 1,
                'za_coida_applicable': 1,
                'za_variable_pay_treatment': 'Once-Off Full Tax'}}

