"""Conservative payroll master-data defaults extracted from za_local."""

# SARS payroll source codes per the SARS PAYE BRS v25.3.0 (effective 1 March 2026).
# Retired codes are kept inactive so existing mappings fail visibly instead of silently.
DEFAULT_SARS_PAYROLL_CODES = [
	{
		"code": "3601",
		"description": "Income - Gross remuneration (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 10,
	},
	{
		"code": "3605",
		"description": "Income - Annual payment (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 20,
	},
	{
		"code": "3606",
		"description": "Income - Commission (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 30,
	},
	{
		"code": "3607",
		"description": "Income - Overtime (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 40,
	},
	{
		"code": "3701",
		"description": "Allowance - Travel allowance (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 50,
	},
	{
		"code": "3702",
		"description": "Allowance - Reimbursive travel allowance, portion not exceeding the prescribed rate (IT)",
		"category": "Income",
		"tax_treatment": "Non-Taxable",
		"active": 1,
		"print_sequence": 60,
	},
	{
		"code": "3703",
		"description": "Allowance - Reimbursive travel allowance at or below the prescribed rate, no other travel compensation (Excl)",
		"category": "Income",
		"tax_treatment": "Non-Taxable",
		"active": 1,
		"print_sequence": 65,
	},
	{
		"code": "3704",
		"description": "Allowance - Subsistence allowance, local travel (IT)",
		"category": "Income",
		"tax_treatment": "Non-Taxable",
		"active": 1,
		"print_sequence": 70,
	},
	{
		"code": "3713",
		"description": "Allowance - Other allowances (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 80,
	},
	{
		"code": "3714",
		"description": "Allowance - Other non-taxable allowances (Excl)",
		"category": "Income",
		"tax_treatment": "Non-Taxable",
		"active": 1,
		"print_sequence": 90,
	},
	{
		"code": "3722",
		"description": "Allowance - Reimbursive travel allowance, portion exceeding the prescribed rate (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 100,
	},
	{
		"code": "3801",
		"description": "Fringe benefit - General fringe benefits (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 110,
	},
	{
		"code": "3802",
		"description": "Fringe benefit - Use of motor vehicle (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 120,
	},
	{
		"code": "3805",
		"description": "Fringe benefit - Accommodation (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 130,
	},
	{
		"code": "3810",
		"description": "Fringe benefit - Medical aid contributions paid by the employer (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 140,
	},
	{
		"code": "3817",
		"description": "Fringe benefit - Employer pension fund contributions (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 150,
	},
	{
		"code": "3825",
		"description": "Fringe benefit - Employer provident fund contributions (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 160,
	},
	{
		"code": "3828",
		"description": "Fringe benefit - Employer retirement annuity fund contributions (PAYE)",
		"category": "Income",
		"tax_treatment": "Taxable",
		"active": 1,
		"print_sequence": 170,
	},
	{
		"code": "3901",
		"description": "Lump sum - Gratuities / severance benefits (directive)",
		"category": "Income",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 180,
	},
	{
		"code": "3907",
		"description": "Lump sum - Other lump sums (directive)",
		"category": "Income",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 190,
	},
	{
		"code": "4001",
		"description": "Deduction - Pension fund contributions paid and deemed paid by employee",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 200,
	},
	{
		"code": "4003",
		"description": "Deduction - Provident fund contributions paid and deemed paid by employee",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 210,
	},
	{
		"code": "4005",
		"description": "Deduction - Medical scheme fees paid and deemed paid by employee",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 220,
	},
	{
		"code": "4006",
		"description": "Deduction - Retirement annuity fund contributions paid and deemed paid by employee",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 230,
	},
	{
		"code": "4102",
		"description": "Deduction - PAYE",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 240,
	},
	{
		"code": "4115",
		"description": "Deduction - Tax on retirement lump sum and severance benefits",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 250,
	},
	{
		"code": "4116",
		"description": "Tax credit - Medical scheme fees tax credit",
		"category": "Tax Credit",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 260,
	},
	{
		"code": "4118",
		"description": "Tax credit - Employment tax incentive",
		"category": "Tax Credit",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 270,
	},
	{
		"code": "4120",
		"description": "Tax credit - Additional medical expenses tax credit",
		"category": "Tax Credit",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 280,
	},
	{
		"code": "4141",
		"description": "Contribution - UIF (employee and employer)",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 290,
	},
	{
		"code": "4142",
		"description": "Employer contribution - SDL",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 300,
	},
	{
		"code": "4472",
		"description": "Employer contribution - Pension fund",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 310,
	},
	{
		"code": "4473",
		"description": "Employer contribution - Provident fund",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 320,
	},
	{
		"code": "4474",
		"description": "Employer contribution - Medical scheme fees",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 330,
	},
	{
		"code": "4475",
		"description": "Employer contribution - Retirement annuity fund",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 340,
	},
	{
		"code": "4493",
		"description": "Employer contribution - Medical scheme fees, retired or former employee (no-value benefit)",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 1,
		"print_sequence": 350,
	},
	{
		"code": "4007",
		"description": "Retired - arrear retirement annuity contributions; not applicable from the 2017 year of assessment",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 0,
		"print_sequence": 360,
	},
	{
		"code": "4008",
		"description": "Retired - not a SARS BRS source code",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 0,
		"print_sequence": 370,
	},
	{
		"code": "4010",
		"description": "Retired - not a SARS BRS source code",
		"category": "Deduction",
		"tax_treatment": "Reference",
		"active": 0,
		"print_sequence": 380,
	},
	{
		"code": "4476",
		"description": "Retired - not a SARS BRS source code",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 0,
		"print_sequence": 390,
	},
	{
		"code": "4477",
		"description": "Retired - not a SARS BRS source code",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 0,
		"print_sequence": 400,
	},
	{
		"code": "4497",
		"description": "Retired - 4497 is the BRS total of deductions and contributions, not a source code",
		"category": "Employer Contribution",
		"tax_treatment": "Reference",
		"active": 0,
		"print_sequence": 410,
	},
]

DEFAULT_SALARY_COMPONENT_SARS_CODES = {
	"Basic Salary": "3601",
	"Basic": "3601",
	"Gross Salary": "3601",
	"Bonus": "3605",
	"Annual Bonus": "3605",
	"Performance Bonus": "3605",
	"Commission": "3606",
	"13th Cheque": "3605",
	"Overtime": "3607",
	"Travel Allowance": "3701",
	"Transport Allowance": "3701",
	"Housing Allowance": "3713",
	"Accommodation Allowance": "3713",
	"Cell Phone Allowance": "3713",
	"Subsistence Allowance": "3704",
	"Business Reimbursement": "3704",
	"Uniform Allowance": "3713",
	"Company Car Benefit": "3802",
	# The PAYE adjustment narrows the 3802 cash equivalent to its PAYE-inclusion
	# portion. It is excluded from IRP5, but payroll still requires every earning to
	# carry a code, so it shares the benefit's code.
	"Company Car PAYE Adjustment": "3802",
	"Use of Motor Vehicle": "3802",
	"Housing Fringe Benefit": "3805",
	"Low Interest Loan Fringe Benefit": "3801",
	"Other Fringe Benefit": "3801",
	"PAYE": "4102",
	"Income Tax": "4102",
	"Employment Tax Incentive": "4118",
	"ETI": "4118",
	"UIF Employee Contribution": "4141",
	"UIF Employer Contribution": "4141",
	"UIF": "4141",
	"SDL Contribution": "4142",
	"SDL": "4142",
	"Skills Development Levy": "4142",
	"Pension Fund": "4001",
	"Provident Fund": "4003",
	"Retirement Fund": "4001",
	"Retirement Annuity Fund": "4006",
	"Medical Aid": "4005",
	# The employer's contribution is a 3810 fringe benefit of the employee. The IRP5
	# reports the employer contribution under 4474 (equal to 3810) and includes it
	# in 4005 as deemed paid by the employee (BRS v25.3.0).
	"Medical Aid Company Contribution": "3810",
	"Medical Aid Contribution": "4005",
	"Medical Scheme": "4005",
	"Medical Insurance": "4005",
	"Severance Benefit": "3901",
	"Leave Payout": "3605",
	"Notice Pay": "3601",
	"Tax on Lump Sum": "4115",
}

DEFAULT_IRP5_EXCLUDED_SALARY_COMPONENTS = {
	"Garnishee Order",
	"Company Car PAYE Adjustment",
	"Union Subscription",
}

FRINGE_BENEFIT_SALARY_COMPONENTS = {
	"Company Car Benefit",
	"Company Car PAYE Adjustment",
	"Housing Fringe Benefit",
	"Low Interest Loan Fringe Benefit",
	"Other Fringe Benefit",
}

DEFAULT_SALARY_COMPONENT_TREATMENTS = {
	"Basic": {
		"za_payroll_treatment": "Regular Remuneration",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
	},
	"Basic Salary": {
		"za_payroll_treatment": "Regular Remuneration",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
	},
	"Company Car Benefit": {
		"za_payroll_treatment": "Regular Remuneration",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 0,
	},
	"Company Car PAYE Adjustment": {
		"za_payroll_treatment": "Regular Remuneration",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 0,
		# The adjustment brings the car benefit to its PAYE inclusion (80%). SDL is
		# levied on the same balance of remuneration, so the reduction applies to it.
		"za_sdl_applicable": 1,
		"za_coida_applicable": 0,
	},
	"Housing Fringe Benefit": {
		"za_payroll_treatment": "Regular Remuneration",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 0,
	},
	"Low Interest Loan Fringe Benefit": {
		"za_payroll_treatment": "Regular Remuneration",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 0,
	},
	"Other Fringe Benefit": {
		"za_payroll_treatment": "Regular Remuneration",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 0,
	},
	"PAYE": {
		"za_payroll_treatment": "PAYE",
		"za_paye_inclusion_percentage": 0,
		"za_uif_applicable": 0,
		"za_sdl_applicable": 0,
		"za_coida_applicable": 0,
	},
	"UIF Employee Contribution": {
		"za_payroll_treatment": "UIF",
		"za_paye_inclusion_percentage": 0,
		"za_uif_applicable": 0,
		"za_sdl_applicable": 0,
		"za_coida_applicable": 0,
	},
	"UIF Employer Contribution": {
		"za_payroll_treatment": "UIF",
		"za_paye_inclusion_percentage": 0,
		"za_uif_applicable": 0,
		"za_sdl_applicable": 0,
		"za_coida_applicable": 0,
	},
	"SDL Contribution": {
		"za_payroll_treatment": "SDL",
		"za_paye_inclusion_percentage": 0,
		"za_uif_applicable": 0,
		"za_sdl_applicable": 0,
		"za_coida_applicable": 0,
	},
	"Transport Allowance": {
		"za_payroll_treatment": "Fixed Travel Allowance",
		"za_paye_inclusion_percentage": 80,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
	},
	"Travel Allowance": {
		"za_payroll_treatment": "Fixed Travel Allowance",
		"za_paye_inclusion_percentage": 80,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
	},
	"Performance Bonus": {
		"za_payroll_treatment": "Annual Payment",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
		"za_variable_pay_treatment": "Once-Off Full Tax",
	},
	"13th Cheque": {
		"za_payroll_treatment": "Annual Payment",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
		"za_variable_pay_treatment": "Once-Off Full Tax",
	},
	"Commission": {
		"za_payroll_treatment": "Commission",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
		"za_variable_pay_treatment": "Once-Off Full Tax",
	},
	"Overtime": {
		"za_payroll_treatment": "Overtime",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
		"za_variable_pay_treatment": "Once-Off Full Tax",
	},
	"Medical Aid Contribution": {
		"za_payroll_treatment": "Medical Aid",
		"za_paye_inclusion_percentage": 0,
		"za_uif_applicable": 0,
		"za_sdl_applicable": 0,
		"za_coida_applicable": 0,
	},
	"Employee Pension Fund Contribution": {
		"za_payroll_treatment": "Retirement Fund",
		"za_paye_inclusion_percentage": 0,
		"za_uif_applicable": 0,
		"za_sdl_applicable": 0,
		"za_coida_applicable": 0,
	},
	"Severance Benefit": {
		"za_payroll_treatment": "Severance Benefit",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 0,
		"za_sdl_applicable": 0,
		"za_coida_applicable": 0,
		"za_variable_pay_treatment": "Manual Review",
	},
	"Leave Payout": {
		"za_payroll_treatment": "Leave Payout",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
		"za_variable_pay_treatment": "Once-Off Full Tax",
	},
	"Notice Pay": {
		"za_payroll_treatment": "Notice Pay",
		"za_paye_inclusion_percentage": 100,
		"za_uif_applicable": 1,
		"za_sdl_applicable": 1,
		"za_coida_applicable": 1,
		"za_variable_pay_treatment": "Once-Off Full Tax",
	},
}
